apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: isidroalfonsin/my-app:1ff0b0234373b6662d7da1d05262b3548e571a20
        ports:
        - containerPort: 80
        imagePullPolicy: Always
